export const LogAction = {
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  PROFILE_UPDATE: "PROFILE_UPDATE",
  PROFILE_DELETE: "PROFILE_DELETE",
  CHECKOUT_REQUEST: "CHECKOUT_REQUEST",
  CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
  CHECKOUT_FAILURE: "CHECKOUT_FAILURE",
  BALANCE_ADJUSTMENT: "BALANCE_ADJUSTMENT",
  PRODUCT_CSV_IMPORT: "PRODUCT_CSV_IMPORT",
} as const;

export type LogActionType = (typeof LogAction)[keyof typeof LogAction];
