services:
  postgres:
    image: postgres:16-alpine
    container_name: lignum-design-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lignum_design
    volumes:
      - lignum_postgres_data:/var/lib/postgresql/data

volumes:
  lignum_postgres_data:
