export const LOG_ACTIONS = {
  LOGIN_SUCCESS: "auth.login.success",
  LOGIN_FAILED: "auth.login.failed",
  REGISTER_SUCCESS: "auth.register.success",
  REGISTER_FAILED: "auth.register.failed",
  LOGOUT: "auth.logout",
  PROFILE_UPDATE: "profile.update",
  PROFILE_DELETE: "profile.delete",
  PROFILE_AVATAR_UPLOAD: "profile.avatar.upload",
  CHECKOUT_SUCCESS: "transaction.checkout.success",
  CHECKOUT_FAILED: "transaction.checkout.failed",
  CHECKOUT_INSUFFICIENT: "transaction.checkout.insufficient_balance",
  CART_ADD: "cart.add",
  REVIEW_CREATE: "review.create",
  REVIEW_DELETE: "review.delete",
  ADMIN_USER_UPDATE: "admin.user.update",
  ADMIN_USER_DELETE: "admin.user.delete",
  ADMIN_BALANCE_ADJUST: "admin.balance.adjust",
  ADMIN_PRODUCT_CREATE: "admin.product.create",
  ADMIN_PRODUCT_UPDATE: "admin.product.update",
  ADMIN_PRODUCT_DELETE: "admin.product.delete",
  ADMIN_PRODUCT_CSV_IMPORT: "admin.product.csv_import",
} as const;
