env:
  contexts:
    - name: auth
      urls:
        - "{{TARGET_URL}}"
      includePaths:
        - "{{TARGET_URL}}.*"
  parameters:
    failOnError: false
    progressToStdout: true
jobs:
{{HOST_REPLACER_JOB}}
{{AUTH_SETUP_JOBS}}
  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 10
  - type: spider
    parameters:
      context: auth
      url: "{{TARGET_URL}}"
      maxDuration: 5
  - type: passiveScan-wait
    parameters:
      maxDuration: 10
  - type: activeScan-config
    parameters:
      threadPerHost: 1
      maxRuleDurationInMins: 3
      maxScanDurationInMins: 15
      maxAlertsPerRule: 10
  - type: activeScan
    parameters:
      context: auth
      threadPerHost: 1
      delayInMs: 300
      maxScanDurationInMins: 15
  - type: passiveScan-wait
    parameters:
      maxDuration: 5
  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk/
      reportFile: auth-report.html
      reportTitle: ZAP Authenticated Scan Report
  - type: report
    parameters:
      template: traditional-json
      reportDir: /zap/wrk/
      reportFile: auth-alerts-raw.json
      reportTitle: ZAP Authenticated Alerts
